name: Generate go.sum

on:
  push:
    branches: [main]
    paths: [go.mod]

permissions:
  contents: write

jobs:
  gosum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.1"
      - run: go mod tidy
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update go.sum"
          file_pattern: go.sum
